### ISSUE TITLE
FindAllFloor掉樓狀況嚴重

### ISSUE THREAD

**Issue by FizzyElt** [davidleitw/goGamer#2]
只能查到部分的樓，無法完整查出
getPageBody網址正確卻出現網址錯誤

FindAuthorFloor掉樓狀況較輕

**Comment by davidleitw** [comment]
此問題大概是因為一次開太多goroutine導致過度頻繁的Get動作
如果要改善的話可能需要把sleep的時間增加, 或者是用proxy的方式去讓每次發出request的ip的不相同
